## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = "[$user]($style) @ "
show_always = true
style_root = "bold red"
style_user = "bold yellow"

# Second param
[hostname]
disabled = false
format = "ğŸŒ [$hostname]($style) in "
ssh_only = false
style = "bold dimmed green"
trim_at = "-"

# Third param
[directory]
style = "blue"
truncate_to_repo = true
truncation_length = 0

# Fourth param
[sudo]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
#[git_status]
#ahead = "â‡¡${count}"
#behind = "â‡£${count}"
#deleted = "x"
#diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
#style = "white"
[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "â‡¡ $count "
behind = "â‡£ $count "
deleted = "ğŸ—‘ $count "
diverged = "â‡• $count "
stashed = "ğŸ“¦ $count "
modified = "ï“’ $count "
staged = '[ï§ $count ](green)'
renamed = "ï‘š $count "
untracked = "ğŸ¤· â€$count "
style = "bold orange"
# Last param in the first line/row
[cmd_duration]
disabled = true
format = "took [$duration]($style)"
min_time = 1


## SECOND LINE/ROW: Prompt
[character]
error_symbol = "[âœ˜](bold red)"

# Prompt: optional param 1
[time]
disabled = true
format = " ğŸ•™ $time($style)\n"
style = "bright-white"
time_format = "%T"

[c]
format = ""
symbol = "î˜ "

[dart]
symbol = "î™Œ "

[docker_context]
symbol = "ó°¡¨ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ó°Š¢ "

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "î™· "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "ó°™ "

[package]
symbol = "ï£– "

[perl]
symbol = "î™¾ "

[php]
symbol = "ó°ŒŸ "

[python]
symbol = "î˜† "
format = ""

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "îš‹ "

[swift]
symbol = "îš™ "

